on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Get Versions
        id: versions
        uses: torstendittmann/get-semver-action@latest
        with:
          version: '1.0.0-alpha.3'
      - name: Get Major
        run: echo "${{ steps.hello.outputs.major }}"
      - name: Get Minor
        run: echo "${{ steps.hello.outputs.minor }}"
      - name: Get Patch
        run: echo "${{ steps.hello.outputs.patch }}"
      - name: Get Pre-Release
        run: echo "${{ steps.hello.outputs.pre-release }}"