on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Get Versions
        id: versions
        uses: torstendittmann/get-semver-action@main
        with:
          version: '1.0.0-alpha.3'
      - name: Get Major
        run: [[ "${{ steps.versions.outputs.major }}" == "1" ]]
      - name: Get Minor
        run: [[ "${{ steps.versions.outputs.major }}" == "1.0" ]]
      - name: Get Patch
        run: [[ "${{ steps.versions.outputs.major }}" == "1.0.0" ]]
      - name: Get PreRelease
        run: [[ "${{ steps.versions.outputs.major }}" == "1.0.0-alpha.3" ]]
