on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Get Versions
        id: versions
        uses: torstendittmann/get-semver-action@main
        with:
          version: '1.0.0-alpha.3'
      - name: Get Major
        run: echo "${{ steps.versions.outputs.major }}"
      - name: Get Minor
        run: echo "${{ steps.versions.outputs.minor }}"
      - name: Get Patch
        run: echo "${{ steps.versions.outputs.patch }}"
      - name: Get PreRelease
        run: echo "${{ steps.versions.outputs.prerelease }}"