on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Get Versions
        id: versions
        uses: torstendittmann/get-semver-action@main
        with:
          version: '1.0.0-alpha.3'
      - name: Get Major
        run: if [[ "${{ steps.versions.outputs.major }}" == "1" ]]; then exit 0; else exit 1; fi
      - name: Get Minor
        run: if [[ "${{ steps.versions.outputs.minor }}" == "1.0" ]]; then exit 0; else exit 1; fi
      - name: Get Patch
        run: if [[ "${{ steps.versions.outputs.patch }}" == "1.0.0" ]]; then exit 0; else exit 1; fi
      - name: Get PreRelease
        run: if [[ "${{ steps.versions.outputs.prerelease }}" == "1.0.0-alpha.3" ]]; then exit 0; else exit 1; fi